### ISSUE TITLE
Question about codes of loss

### ISSUE THREAD

**Issue by samsara-ku** [hustvl/CrossVIS#10]
Hi, I'm wondering the meaning of codes in this figure. These codes are in the python file `adet/modeling/condinst/crossvis.py`.

![image](https://user-images.githubusercontent.com/59246456/162726733-0022d1bf-60be-454f-820b-7b46992129f3.png)

When I actually run your training code, there is no update with `sem_losses_0`, `proposal_losses_0` and `mask_losses_0` due to updating with `losses` dict, not the `losses_0`.

So based on this situation, I want to ask you two questions: 

1) Did you intend this kind of logic, updating with only one frame?
2) Although I didn't see all iteration of training, based on some iteration, `sem_losses` was empty dict. Is it correct?

**Comment by vealocia** [comment]
Hi, @samsara-ku. Thanks for your interest in our work.
For the first question, this is absolutely a mistake in our core rearrangement. Thanks for Thanks for  pointing this out and I will update the correct code now.
For the second question, the semantic loss is introduced by CondInst and I suggest you to follow the config [here](https://github.com/hustvl/CrossVIS/blob/729baabd146980839544e274387bd5adb4640d03/configs/CondInst/MS_R_101_3x_sem.yaml#L8).

**Comment by samsara-ku** [comment]
Hi again! I'm gonna share a picture for you.

![image](https://user-images.githubusercontent.com/59246456/165114490-b2e9aa29-8ae1-40ea-930f-9e32242d57e4.png)

This image is about vscode debugging tool for your codes where "adet/modeling/condinst/crossvis.py"

I'm wondering to know this is your intention, the empty object `sem_losses`.

This is not only first step result but also `sem_losses` object always empty, which is really weird.

Could you give me any answer for this problem?
