### ISSUE TITLE
CrossVIS   Whether Boxinst is supported for Vis tasks

### ISSUE THREAD

**Issue by Alxx999** [hustvl/CrossVIS#14]

**Comment by vealocia** [comment]
Yes! CrossVIS with BoxInst is just a little lower than CrossVIS with CondInst.

**Comment by Alxx999** [comment]
> 是的！带有 BoxInst 的 CrossVIS 仅比带有 CondInst 的 CrossVIS 低一点

Ok, do I need to change the pre-training weight to boxInst_MS_R_50_3x.pth when using BoxInst?

**Comment by vealocia** [comment]
> > 是的！带有 BoxInst 的 CrossVIS 仅比带有 CondInst 的 CrossVIS 低一点
> 
> Ok, do I need to change the pre-training weight to boxInst_MS_R_50_3x.pth when using BoxInst?

Yes.

**Comment by Alxx999** [comment]
> > > 是的！带有 BoxInst 的 CrossVIS 仅比带有 CondInst 的 CrossVIS 低一点
> > 
> > 
> > Ok, do I need to change the pre-training weight to boxInst_MS_R_50_3x.pth when using BoxInst?
> 
> Yes.

ok! Thank you!
