### ISSUE TITLE
Hello,What do these parameters (fpn_levels_0/1, gt_inds_0/1, inst_im_inds,inst_rel_ids) mean in crossvis.py

### ISSUE THREAD

**Issue by Alxx999** [hustvl/CrossVIS#15]

**Comment by vealocia** [comment]
Hi, @Alxx999! Thanks for your attention in our work.
```fpn_levels``` and ```gt_inds``` indicates the corresponding fpn feature and ground truth for each predicted instance, respectively. You can try running ```CondInst``` to get details. As we sample a pair of frames from one video in a batch, we use 0 and 1 to identify two frames.
```inst_im_inds``` and ```inst_rel_ids``` are used to find the instance relations between a pair of frames.

**Comment by Alxx999** [comment]
> 你好，@Alxx999！感谢您对我们工作的关注。 `fpn_levels`并`gt_inds`分别表示每个预测实例对应的 fpn 特征和ground truth。您可以尝试运行`CondInst`以获取详细信息。当我们从一个视频中批量采样一对帧时，我们使用 0 和 1 来识别两个帧。 `inst_im_inds`并`inst_rel_ids`用于查找一对帧之间的实例关系。

OK！Thank you very much!
