### ISSUE TITLE
Can the results of the training 2019 dataset be uploaded to youtubevos cocoapi for evaluation？

### ISSUE THREAD

**Issue by 15733171319** [hustvl/CrossVIS#18]
Hello, I am very interested in your code, would like to ask if the result of your training 2019 dataset can be uploaded to youtubevos cocoapi for evaluation?

**Comment by vealocia** [comment]
Hi, @15733171319! Thanks for your interest in our work.
YouTube-VIS 2019 dataset does not provide annotations for custom evaluation. You must upload your submission to online evaluation server in codalab to get the final scores.

**Comment by 15733171319** [comment]
> 你好，@15733171319！感谢您对我们的工作感兴趣。 YouTube-VIS 2019 数据集不提供用于自定义评估的注释。您必须将提交的内容上传到 codalab 中的在线评估服务器才能获得最终分数。

Hello, this is the result after I submitted it, what is the reason?
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpZIKrQX/run/program/evaluate.py", line 58, in 
    res = gts.loadRes(submit_file)
  File "build/bdist.linux-x86_64/egg/pycocotools/ytvos.py", line 225, in loadRes
AssertionError: Results do not correspond to current coco set

**Comment by vealocia** [comment]
Your upload file's format maybe invalid.

**Comment by 15733171319** [comment]
> 

alright, thank you very much
