### ISSUE TITLE
About the modification of your dataloader

### ISSUE THREAD

**Issue by HarryHsing** [hustvl/CrossVIS#20]
Hi Vealocia. Could you tell me where can I modify the data loader, so that I can (1) load more than 2 images in a batch (2) load these images in a sequential order instead of randomly?

Thank you very much for your support in advance!

**Comment by HarryHsing** [comment]
I found the solution to my (2)second question by changing `cfg.MODEL.CROSSVIS.CROSSOVER.SAMPLE_REGION`

**Comment by vealocia** [comment]
Question 1 is more complicated. You can try to modifying the dataloader and dataset mapper firstly.

**Comment by vealocia** [comment]
Dataset mapper can be found in [here](https://github.com/hustvl/CrossVIS/blob/378f4f3bddc3539eaad168a2f11af6cb9f38ae34/adet/data/dataset_mapper.py#L229).
And you can sample more images by changing  [here](https://github.com/hustvl/CrossVIS/blob/378f4f3bddc3539eaad168a2f11af6cb9f38ae34/adet/data/common.py#L78)

**Comment by HarryHsing** [comment]
> Dataset mapper can be found in [here](https://github.com/hustvl/CrossVIS/blob/378f4f3bddc3539eaad168a2f11af6cb9f38ae34/adet/data/dataset_mapper.py#L229). And you can sample more images by changing [here](https://github.com/hustvl/CrossVIS/blob/378f4f3bddc3539eaad168a2f11af6cb9f38ae34/adet/data/common.py#L78)

Got it! Thank you for your prompt response, I will try modifying this.

**Comment by fxooooooooo** [comment]
> I found the solution to my (2)second question by changing `cfg.MODEL.CROSSVIS.CROSSOVER.SAMPLE_REGION`

Hello,  **MODEL.CROSSVIS.CROSSOVER.SAMPLE_REGION = 20**  how much should I change to will become sequentially sampled？  I've tried 1 can do it sequentially, but 2 can also do it sequentially, why is that?
