### ISSUE TITLE
参数更新

### ISSUE THREAD

**Issue by 15733171319** [hustvl/CrossVIS#22]
您好，我有个问题想请教你
我在代码中加了个注意力，但是注意力中有nn.Parameter()函数，会产生权重参数，但是权重参数不会更新，需要在优化器设置更新，想问问恩您具体知道优化器在哪里吗？怎么修改？

**Comment by vealocia** [comment]
Hi, @15733171319. 感谢你对我们工作的关注。
CrossVIS项目依托于Detectron2，相应的优化器构建也在Detectron2的代码中，你可以通过修改Detectron2中相关代码来实现对优化器的修改。
此外，如果注意力模块添加得当的话，应该不会出现你描述的这个问题。网络构建后，nn.Parameter会被视为网络参数的一部分，进而被优化器优化，我建议你检查下实现代码和逻辑的一致性。
希望对你的提问有帮助。

**Comment by 15733171319** [comment]
非常感谢您的意见，但是我的代码权重参数确实一直不更新，一直都保持不变，代码我也反复检查，没发现有什么问题
