### ISSUE TITLE
How to verify video or photo

### ISSUE THREAD

**Issue by 15733171319** [hustvl/CrossVIS#27]
Hello author:
I recently read your paper and code, and I want to ask how I can verify the video or picture I shot myself. I want to see the rendering after segmentation. Do you have the relevant code? Thanks!

**Comment by Yuxin-CV** [comment]
Hi, I suggest you converting your test video into youtube-vis format, then get and visualize the predicted `json` file.

**Comment by 15733171319** [comment]
Hello, I would like to ask how to get and visualize the json file

**Comment by vealocia** [comment]
Hi, @15733171319. This repo doesn't include off-the-shelf visualization code. You can simply achieve your target with opencv and matplotlib. [Here](https://github.com/VisualComputingInstitute/mots_tools/blob/master/mots_vis/visualize_mots.py) provides some codes for reference.
