### ISSUE TITLE
x3 Schedule Results

### ISSUE THREAD

**Issue by JialianW** [hustvl/CrossVIS#7]
Dear author,

Thanks for your great open-source work. In the literature that image object detectors on COCO usually try an x3 training schedule. I wonder if you ever trained the method for an x3 training schedule for VIS? Will it further improve results or already saturate in the x1 schedule?

**Comment by Yuxin-CV** [comment]
Hi@JialianW 

We find longer schedule results in even worse results.

Actually, for VIS dataset, usually 5-6 epochs (i.e., 0.5x schedule) finetuning works the best.
