### ISSUE TITLE
How to use tools/visualize_data.py

### ISSUE THREAD

**Issue by crx981113** [hustvl/CrossVIS#8]
Thank you for the great project!!
How can I  use tools/visualize_data.py to visualize the result?

**Comment by vealocia** [comment]
Hi, @crx981113 ! Thanks for your interest in our work.
```tools/visualize_data.py``` is provided by ```detectron2``` to visualize data annotations, so it can't be used to visualize predictions.

**Comment by fxooooooooo** [comment]
> 

So，hello author, what command should I use to visualize the prediction results of a dataset
